# Generated by Django 3.0.8 on 2020-08-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='accessed',
            field=models.BooleanField(default=False, verbose_name='Accessed'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='denied',
            field=models.BooleanField(default=False, verbose_name='Denied'),
        ),
    ]
