# Generated by Django 3.0.8 on 2020-08-10 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0002_auto_20200808_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(verbose_name='Company id')),
                ('saved', models.BooleanField(default=False, verbose_name='Saved')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_restaurants', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'SavedRestaurant',
                'verbose_name_plural': 'SavedRestaurants',
            },
        ),
    ]
