# Generated by Django 3.0.8 on 2020-08-11 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_savedrestaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedrestaurant',
            name='company_id',
        ),
        migrations.AddField(
            model_name='savedrestaurant',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_restaurants', to='restaurant.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_url',
            field=models.URLField(max_length=500, verbose_name='Photo Url'),
        ),
    ]
