# Generated by Django 3.0.8 on 2020-08-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20200811_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_url',
            field=models.URLField(verbose_name='Photo Url'),
        ),
    ]
