# Generated by Django 3.0.8 on 2020-08-11 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20200811_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_comment', to='restaurant.Company', verbose_name='Company'),
        ),
    ]
