# Generated by Django 3.0.8 on 2020-08-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_comment_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='raiting',
            field=models.IntegerField(blank=True, null=True, verbose_name='Raiting'),
        ),
    ]
