# Generated by Django 3.0.8 on 2020-08-13 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20200813_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_img',
        ),
        migrations.CreateModel(
            name='CommentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='comment-images/', verbose_name='Photo')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_photos', to='restaurant.Comment', verbose_name='comment')),
            ],
            options={
                'verbose_name': 'CommentImages',
                'verbose_name_plural': 'CommentImagess',
            },
        ),
    ]
