# Generated by Django 3.0.8 on 2020-08-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_auto_20200816_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='overall',
            field=models.IntegerField(default=1, verbose_name='Overall'),
            preserve_default=False,
        ),
    ]
