# Generated by Django 3.0.8 on 2020-08-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_company_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Cuisine Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cuisines/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Cuisine',
                'verbose_name_plural': 'Cuisines',
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='cuisines',
        ),
        migrations.AddField(
            model_name='company',
            name='cuisine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='restaurant.Cuisine', verbose_name='Cuisine'),
        ),
    ]
