# Generated by Django 3.0.8 on 2020-08-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_auto_20200819_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='accessed',
        ),
        migrations.AddField(
            model_name='reservation',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='Accept'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Reserved at'),
        ),
    ]
