# Generated by Django 3.0.8 on 2020-08-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_auto_20200830_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='table',
            name='dates',
            field=models.ManyToManyField(related_name='tables', to='restaurant.TableDate', verbose_name='Dates'),
        ),
        migrations.AlterField(
            model_name='tabledate',
            name='times',
            field=models.ManyToManyField(related_name='tableDates', to='restaurant.Time', verbose_name='Time'),
        ),
    ]
