# Generated by Django 3.0.8 on 2020-09-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_company_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('accept_reservation', 'Accepted Reservation'), ('new_reservation', 'New Reservation')], max_length=50, null=True, verbose_name='Notification type'),
        ),
    ]
