# Generated by Django 3.0.8 on 2020-09-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='overall',
            field=models.IntegerField(blank=True, null=True, verbose_name='Overall'),
        ),
    ]
